version: 1
env:
  - GO111MODULE=on
  - CGO_ENABLED=0

flags:
  - -trimpath

goos:
  - linux

goarch:
  - amd64

binary: >-
  {{ .ProjectName }}_
  {{- trimprefix .Os "darwin" | trimprefix "linux" | trimprefix "windows" }}_
  {{- .Arch }}

main: ./cmd/gogpt/main.go
ldflags:
  - "-X main.Version={{ .Version }}"

builds:
  - id: gogpt
    binary: gogpt
    main: ./cmd/gogpt/main.go
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -trimpath
    ldflags:
      - "-X main.Version={{ .Version }}"
